Repository Travel-in-nanaland/Back-end, pull requests merged in 2024-05, with the labels that each got.

#110 [Feat] Guest 추가 & JWT 관리 수정 & 로그아웃
  src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java
  src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Provider.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Role.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
  src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/global/auth/AuthMember.java
  src/main/java/com/jeju/nanaland/global/auth/AuthMemberArgumentResolver.java
  src/main/java/com/jeju/nanaland/global/auth/MemberDetailsService.java
  src/main/java/com/jeju/nanaland/global/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/jeju/nanaland/global/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/jeju/nanaland/global/auth/jwt/JWTAuthenticationFilter.java
  src/main/java/com/jeju/nanaland/global/auth/jwt/dto/JwtResponseDto.java
  src/main/java/com/jeju/nanaland/global/config/JwtConfig.java
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
  src/main/java/com/jeju/nanaland/global/config/WebConfig.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/java/com/jeju/nanaland/global/util/JwtUtil.java
  src/main/java/com/jeju/nanaland/global/util/RedisUtil.java
Labels: feat, refactor

#95 [feat] 정보 수정 요청
  build.gradle
  src/main/java/com/jeju/nanaland/domain/report/controller/ReportController.java
  src/main/java/com/jeju/nanaland/domain/report/dto/ReportRequest.java
  src/main/java/com/jeju/nanaland/domain/report/entity/FixType.java
  src/main/java/com/jeju/nanaland/domain/report/entity/InfoFixReport.java
  src/main/java/com/jeju/nanaland/domain/report/repository/InfoFixReportRepository.java
  src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java
  src/main/java/com/jeju/nanaland/global/component/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/resources/templates/info-fix-report.html
  src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
Labels: feat

#146 [Feat] 회원 가입 API, 로그인 API 수정
  src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/ConsentType.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberConsent.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberConsentRepository.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/java/com/jeju/nanaland/global/image_upload/S3Config.java
  src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
  src/main/java/com/jeju/nanaland/global/image_upload/dto/S3ImageDto.java
  src/test/java/com/jeju/nanaland/domain/entity/EntityBuilderTest.java
Labels: feat

#137 [Feat] 회원 프로필 조회, 수정
  src/main/java/com/jeju/nanaland/domain/common/entity/ImageFile.java
  src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberType.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberTypeHashtag.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
  src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
Labels: feat

#155 [Feat] 나나스픽 검색 범위 수정
  src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
Labels: feat

#157 [Feat] 언어 변경 확인 후 업데이트
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
Labels: feat

#162 [Feat] 이메일 unique 제거, 회원 가입 및 로그인 로직 중 이메일 관련 로직 제거
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
Labels: feat

#179 [Refactor] 패키지 수정
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
Labels: refactor

#174 [Feat] 만료된 약관 동의 false 처리
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java
Labels: feat

#176 [Feat] 닉네임, 소개글 글자 제한 추가
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
Labels: feat

#189 [Feat] providerId 타입을 String으로 변경
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/test/java/com/jeju/nanaland/domain/entity/EntityImageFileMappingTest.java
  src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java
  src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
  src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
  src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
  src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
Labels: feat

#196 [Feat] 이용약관 수정 API
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
Labels: feat

#203 [Feat] 회원 정보 조회에 이용약관 추가
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberConsent.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
Labels: feat

#204 [Feat] 이용약관 생성 및 수정 로직 수정
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
Labels: feat

#207 [Feat] 비회원 이용약관 로직 수정 & 회원 탈퇴 조회 로직 수정 & 강제 회원 탈퇴 API
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberWithdrawal.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberWithdrawalRepository.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
Labels: feat, fix

#208 [#206] feat: memberId가 아닌 토큰으로 변경
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
Labels: refactor

#210 [Fix] 본인의 닉네임과 중복되는 오류 해결
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
Labels: fix

#215 [Feat] 7대 자연 리스트 조회에 keyword 추가
  src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
Labels: feat
