Repository Travel-in-nanaland/Back-end, pull requests merged in 2024-09, with the labels that each got.

#393 Refactor/#389 s3 image service
  src/main/java/com/jeju/nanaland/domain/common/service/ImageFileService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
  src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
  src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
  src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java
  src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java
  src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
  src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
Labels: refactor

#391 [Refactor] member 리팩토링
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberWithdrawal.java
  src/main/java/com/jeju/nanaland/domain/member/entity/enums/TravelType.java
  src/main/java/com/jeju/nanaland/domain/member/entity/enums/WithdrawalType.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberConsentService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
  src/main/java/com/jeju/nanaland/domain/notification/service/FcmTokenService.java
  src/main/java/com/jeju/nanaland/global/auth/AuthMemberArgumentResolver.java
  src/main/java/com/jeju/nanaland/global/image_upload/S3ImageService.java
  src/main/java/com/jeju/nanaland/global/util/JwtUtil.java
  src/test/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryTest.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberConsentServiceTest.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberLoginServiceTest.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
Labels: refactor

#404 [Refactor] 공지사항(notice) 리팩토링
  src/main/java/com/jeju/nanaland/domain/notice/controller/NoticeController.java
  src/main/java/com/jeju/nanaland/domain/notice/dto/NoticeResponse.java
  src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/notice/service/NoticeService.java
  src/test/java/com/jeju/nanaland/domain/notice/repository/NoticeRepositoryImplTest.java
  src/test/java/com/jeju/nanaland/domain/notice/service/NoticeServiceTest.java
Labels: refactor, test

#399 [Refactor] Favorite 도메인 Dto 컨벤션 적용
  src/main/java/com/jeju/nanaland/domain/common/dto/PostPreviewDto.java
  src/main/java/com/jeju/nanaland/domain/common/service/PostService.java
  src/main/java/com/jeju/nanaland/domain/common/service/PostServiceImpl.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java
  src/main/java/com/jeju/nanaland/domain/favorite/controller/FavoriteController.java
  src/main/java/com/jeju/nanaland/domain/favorite/dto/FavoritePostCardDto.java
  src/main/java/com/jeju/nanaland/domain/favorite/dto/FavoriteResponse.java
  src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java
  src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
  src/main/java/com/jeju/nanaland/domain/notification/service/FavoriteNotificationService.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java
  src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java
  src/test/java/com/jeju/nanaland/domain/favorite/service/FavoriteServiceTest.java
  src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
  src/test/java/com/jeju/nanaland/domain/restaurant/service/RestaurantServiceTest.java
Labels: refactor, test

#406 [Refactor] 7대 자연(Nature) 리팩토링
  src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java
  src/main/java/com/jeju/nanaland/domain/nature/dto/NatureResponse.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
  src/main/java/com/jeju/nanaland/domain/report/service/ReportService.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
  src/test/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryTest.java
  src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
  src/test/java/com/jeju/nanaland/domain/report/service/ReportServiceTest.java
Labels: refactor, test

#413 [Fix] 닉네임 유효 확인 API permitAll 적용
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
Labels: fix

#415 [Feat] 리뷰 좋아요 여부 추가
  src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java
  src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
Labels: feat

#425 [Hotfix] 추천게시물 별도 제목 추가
  src/main/java/com/jeju/nanaland/domain/member/entity/RecommendTrans.java
  src/main/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryImpl.java
  src/test/java/com/jeju/nanaland/domain/member/repository/RecommendRepositoryTest.java
Labels: hotfix
