Repository Travel-in-nanaland/Back-end, pull requests merged in 2024-04, with the labels that each got.

#20 [Feat] 로그인 기능 구현
  build.gradle
  src/main/java/com/jeju/nanaland/domain/common/entity/Language.java
  src/main/java/com/jeju/nanaland/domain/common/entity/Locale.java
  src/main/java/com/jeju/nanaland/domain/common/repository/LanguageRepository.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Provider.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/global/config/RedisConfig.java
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/java/com/jeju/nanaland/global/jwt/JWTAuthenticationFilter.java
  src/main/java/com/jeju/nanaland/global/jwt/JwtConfig.java
  src/main/java/com/jeju/nanaland/global/jwt/JwtProvider.java
  src/main/java/com/jeju/nanaland/global/jwt/MemberDetailsService.java
  src/main/java/com/jeju/nanaland/global/jwt/dto/JwtResponseDto.java
  src/main/java/com/jeju/nanaland/global/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/jeju/nanaland/global/jwt/handler/CustomAuthenticationEntryPoint.java
  src/test/java/com/jeju/nanaland/domain/entity/EntityBuilderTest.java
  src/test/java/com/jeju/nanaland/domain/entity/EntityImageFileMappingTest.java
Labels: feat, chore

#28 [Feat] Jwt 생성 및 검증 부분 수정, 커스텀 어노테이션 추가
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/global/config/SecurityConfig.java
  src/main/java/com/jeju/nanaland/global/config/WebConfig.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
  src/main/java/com/jeju/nanaland/global/jwt/AuthMember.java
  src/main/java/com/jeju/nanaland/global/jwt/AuthMemberArgumentResolver.java
  src/main/java/com/jeju/nanaland/global/jwt/JWTAuthenticationFilter.java
  src/main/java/com/jeju/nanaland/global/jwt/JwtUtil.java
Labels: feat, refactor

#25 [Feat] 검색 결과 조회
  gradlew
  src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValid.java
  src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValidator.java
  src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepository.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepository.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/market/dto/MarketCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/market/entity/MarketTrans.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepository.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/entity/MemberType.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberTypeService.java
  src/main/java/com/jeju/nanaland/domain/nature/dto/NatureCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepository.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
  src/main/java/com/jeju/nanaland/domain/stay/entity/Stay.java
  src/main/java/com/jeju/nanaland/domain/stay/entity/StayTrans.java
  src/main/java/com/jeju/nanaland/global/BaseResponse.java
  src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/main/java/com/jeju/nanaland/global/jwt/AuthMember.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberTypeServiceTest.java
Labels: feat

#31 [#30] feat: 인기 검색어 조회
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
Labels: feat

#35 [#34] refactor: search 컨트롤러 pageable 객체 제거
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
Labels: refactor

#37 [#16] refactor: s3 업로드 메서드 별도 구현
  src/main/java/com/jeju/nanaland/global/imageUpload/S3ImageService.java
Labels: refactor

#36 [Feat] 로그인 회원 생성 로직 수정
  src/main/java/com/jeju/nanaland/domain/common/annotation/EnumValidator.java
  src/main/java/com/jeju/nanaland/domain/common/entity/Locale.java
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberRequest.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Provider.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepository.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/member/repository/MemberRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberLoginService.java
  src/main/java/com/jeju/nanaland/global/exception/ConflictException.java
  src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
Labels: fix

#56 [#55] Feat : 검색 결과에 좋아요 여부 반환
  src/main/java/com/jeju/nanaland/domain/common/data/CategoryContent.java
  src/main/java/com/jeju/nanaland/domain/common/entity/Category.java
  src/main/java/com/jeju/nanaland/domain/common/repository/CategoryRepository.java
  src/main/java/com/jeju/nanaland/domain/experience/controller/ExperienceController.java
  src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceRequest.java
  src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceResponse.java
  src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java
  src/main/java/com/jeju/nanaland/domain/favorite/repository/FavoriteRepository.java
  src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
  src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java
  src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java
  src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java
  src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java
  src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
  src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
  src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java
  src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/test/java/com/jeju/nanaland/domain/entity/EntityImageFileMappingTest.java
  src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java
  src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
  src/test/java/com/jeju/nanaland/domain/search/service/SearchServiceTest.java
Labels: feat

#74 [Feat] addressTag 추가
  src/main/java/com/jeju/nanaland/domain/common/entity/CommonTrans.java
  src/main/java/com/jeju/nanaland/domain/experience/dto/ExperienceCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/experience/entity/ExperienceTrans.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/festival/dto/FestivalCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/festival/entity/FestivalTrans.java
  src/main/java/com/jeju/nanaland/domain/festival/repository/FestivalRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/market/dto/MarketCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/market/entity/MarketTrans.java
  src/main/java/com/jeju/nanaland/domain/market/repository/MarketRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nature/dto/NatureCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/nature/entity/NatureTrans.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
Labels: feat

#67 [Refactor] : 게시물 좋아요 토글 반환형에 boolean favorite 추가
  src/main/java/com/jeju/nanaland/domain/experience/controller/ExperienceController.java
  src/main/java/com/jeju/nanaland/domain/experience/service/ExperienceService.java
  src/main/java/com/jeju/nanaland/domain/favorite/dto/FavoriteResponse.java
  src/main/java/com/jeju/nanaland/domain/favorite/service/FavoriteService.java
  src/main/java/com/jeju/nanaland/domain/festival/controller/FestivalController.java
  src/main/java/com/jeju/nanaland/domain/festival/service/FestivalService.java
  src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java
  src/main/java/com/jeju/nanaland/domain/market/service/MarketService.java
  src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
  src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
  src/main/java/com/jeju/nanaland/domain/nature/controller/NatureController.java
  src/main/java/com/jeju/nanaland/domain/nature/service/NatureService.java
  src/test/java/com/jeju/nanaland/domain/experience/service/ExperienceServiceTest.java
  src/test/java/com/jeju/nanaland/domain/festival/service/FestivalServiceTest.java
  src/test/java/com/jeju/nanaland/domain/market/service/MarketServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
  src/test/java/com/jeju/nanaland/domain/nature/service/NatureServiceTest.java
Labels: refactor

#69 [Feat] 7대 자연 리스트, 상세 조회
  src/main/java/com/jeju/nanaland/domain/market/controller/MarketController.java
  src/main/java/com/jeju/nanaland/domain/nature/repository/NatureRepositoryImpl.java
Labels: feat
