Repository Travel-in-nanaland/Back-end, pull requests merged in 2024-07, with the labels that each got.

#301 [Test] review list 테스트 코드
  src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java
  src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
  src/test/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImplTest.java
  src/test/java/com/jeju/nanaland/domain/review/service/ReviewServiceTest.java
Labels: feat, test

#299 [Feat] 맛집 리스트 조회, 상세조회
  src/main/java/com/jeju/nanaland/domain/common/data/Category.java
  src/main/java/com/jeju/nanaland/domain/restaurant/controller/RestaurantController.java
  src/main/java/com/jeju/nanaland/domain/restaurant/converter/RestaurantTypeKeywordConverter.java
  src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantResponse.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/Restaurant.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantKeyword.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantMenu.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantTrans.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/enums/RestaurantTypeKeyword.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepository.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java
  src/main/java/com/jeju/nanaland/global/exception/ErrorCode.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
Labels: feat

#304 [Feat] 유저 프로필 조회 수정
  src/main/java/com/jeju/nanaland/domain/member/controller/MemberController.java
  src/main/java/com/jeju/nanaland/domain/member/dto/MemberResponse.java
  src/main/java/com/jeju/nanaland/domain/member/entity/Member.java
  src/main/java/com/jeju/nanaland/domain/member/service/MemberProfileService.java
  src/test/java/com/jeju/nanaland/domain/member/service/MemberProfileServiceTest.java
Labels: feat, test

#307 [Refactor] 500 error
  src/main/java/com/jeju/nanaland/global/exception/ControllerAdvice.java
Labels: refactor

#308 [Feat] 회원별 리뷰 리스트 조회
  src/main/java/com/jeju/nanaland/domain/review/controller/ReviewController.java
  src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java
  src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/review/repository/ReviewRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java
  src/test/java/com/jeju/nanaland/domain/review/service/ReviewServiceTest.java
Labels: feat, test

#309 Feat/#306 review search auto complete
  src/main/java/com/jeju/nanaland/domain/common/data/Category.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/experience/repository/ExperienceRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/review/controller/ReviewController.java
  src/main/java/com/jeju/nanaland/domain/review/dto/ReviewResponse.java
  src/main/java/com/jeju/nanaland/domain/review/service/ReviewService.java
  src/main/java/com/jeju/nanaland/global/config/RedisConfig.java
Labels: feat

#327 [Refactor] 맛집 상세조회 service 정보 추가
  src/main/java/com/jeju/nanaland/domain/experience/entity/enums/ExperienceTypeKeyword.java
  src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantCompositeDto.java
  src/main/java/com/jeju/nanaland/domain/restaurant/dto/RestaurantResponse.java
  src/main/java/com/jeju/nanaland/domain/restaurant/entity/RestaurantTrans.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/restaurant/service/RestaurantService.java
Labels: feat

#328 [Feat] 맛집 검색 추가
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/restaurant/repository/RestaurantRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/search/controller/SearchController.java
  src/main/java/com/jeju/nanaland/domain/search/dto/SearchResponse.java
  src/main/java/com/jeju/nanaland/domain/search/service/SearchService.java
Labels: feat

#325 Refactor/#324 nana pick api
  src/main/java/com/jeju/nanaland/domain/nana/controller/NanaController.java
  src/main/java/com/jeju/nanaland/domain/nana/dto/NanaResponse.java
  src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryCustom.java
  src/main/java/com/jeju/nanaland/domain/nana/repository/NanaRepositoryImpl.java
  src/main/java/com/jeju/nanaland/domain/nana/service/NanaService.java
  src/main/java/com/jeju/nanaland/global/exception/SuccessCode.java
  src/test/java/com/jeju/nanaland/domain/nana/service/NanaServiceTest.java
Labels: feat
